# A generic Alembic configuration file.
# Refer to the Alembic documentation at http://alembic.zzzcomputing.com
# for complete details.

[alembic]
# Esta es la ruta a tus scripts de migración.
script_location = alembic

# Esta línea le dice a Alembic que busque tu código fuente en la carpeta raíz.
# Asegúrate de que solo aparezca UNA VEZ.
prepend_sys_path = .

# URL de tu base de datos.
sqlalchemy.url = postgresql://postgres:B3ll1c0s@localhost:5432/ges_neu_bd


# Logging configuration.
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
