# pyproject.toml

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function" 
# ...
markers = [
    # --- Añade o descomenta esta línea ---
    "integration: mark test as integration test (requires PostgreSQL test DB)",
    # ------------------------------------
    # "asyncio", # Mantén otros si los tenías
]