# schemas/common.py
from enum import Enum

class EstadoNeumaticoEnum(str, Enum):
    EN_STOCK = "EN_STOCK"; INSTALADO = "INSTALADO"; EN_REPARACION = "EN_REPARACION"; EN_REENCAUCHE = "EN_REENCAUCHE"; DESECHADO = "DESECHADO"; EN_TRANSITO = "EN_TRANSITO"
class LadoVehiculoEnum(str, Enum):
    IZQUIERDO = "IZQUIERDO"; DERECHO = "DERECHO"; CENTRAL = "CENTRAL"; INDETERMINADO = "INDETERMINADO"
class TipoEjeEnum(str, Enum):
    DIRECCION = "DIRECCION"; TRACCION = "TRACCION"; LIBRE = "LIBRE"; PORTADOR = "PORTADOR"; ARRASTRE = "ARRASTRE"
class TipoEventoNeumaticoEnum(str, Enum):
    COMPRA = "COMPRA"; INSTALACION = "INSTALACION"; DESMONTAJE = "DESMONTAJE"; INSPECCION = "INSPECCION"; ROTACION = "ROTACION"; REPARACION_ENTRADA = "REPARACION_ENTRADA"; REPARACION_SALIDA = "REPARACION_SALIDA"; REENCAUCHE_ENTRADA = "REENCAUCHE_ENTRADA"; REENCAUCHE_SALIDA = "REENCAUCHE_SALIDA"; DESECHO = "DESECHO"; AJUSTE_INVENTARIO = "AJUSTE_INVENTARIO"
class TipoProveedorEnum(str, Enum):
    FABRICANTE = "FABRICANTE"; DISTRIBUIDOR = "DISTRIBUIDOR"; SERVICIO_REPARACION = "SERVICIO_REPARACION"; SERVICIO_REENCAUCHE = "SERVICIO_REENCAUCHE"; OTRO = "OTRO"