# schemas/common.py
from enum import Enum


class EstadoNeumaticoEnum(str, Enum):
    EN_STOCK = "EN_STOCK"; INSTALADO = "INSTALADO"; EN_REPARACION = "EN_REPARACION"; EN_REENCAUCHE = "EN_REENCAUCHE"; DESECHADO = "DESECHADO"; EN_TRANSITO = "EN_TRANSITO"
class LadoVehiculoEnum(str, Enum):
    IZQUIERDO = "IZQUIERDO"; DERECHO = "DERECHO"; CENTRAL = "CENTRAL"; INDETERMINADO = "INDETERMINADO"
class TipoEjeEnum(str, Enum):
    DIRECCION = "DIRECCION"; TRACCION = "TRACCION"; LIBRE = "LIBRE"; PORTADOR = "PORTADOR"; ARRASTRE = "ARRASTRE"
class TipoEventoNeumaticoEnum(str, Enum):
    COMPRA = "COMPRA"
    INSTALACION = "INSTALACION"
    DESMONTAJE = "DESMONTAJE"
    INSPECCION = "INSPECCION"
    ROTACION = "ROTACION"
    REPARACION_ENTRADA = "REPARACION_ENTRADA"
    REPARACION_SALIDA = "REPARACION_SALIDA"
    REENCAUCHE_ENTRADA = "REENCAUCHE_ENTRADA"
    REENCAUCHE_SALIDA = "REENCAUCHE_SALIDA"
    DESECHO = "DESECHO"
    AJUSTE_INVENTARIO = "AJUSTE_INVENTARIO"
    # --- *** AÑADIR ESTA LÍNEA *** ---
    TRANSFERENCIA_UBICACION = "TRANSFERENCIA_UBICACION"
    # ---------------------------------
class TipoProveedorEnum(str, Enum):
    FABRICANTE = "FABRICANTE"; DISTRIBUIDOR = "DISTRIBUIDOR"; SERVICIO_REPARACION = "SERVICIO_REPARACION"; SERVICIO_REENCAUCHE = "SERVICIO_REENCAUCHE"; OTRO = "OTRO"

# --- AÑADIR ESTE ENUM ---
class TipoParametroEnum(str, Enum):
    PROFUNDIDAD_MINIMA = "PROFUNDIDAD_MINIMA"
    STOCK_MINIMO = "STOCK_MINIMO"
    STOCK_MAXIMO = "STOCK_MAXIMO"
    VIDA_UTIL_KM = "VIDA_UTIL_KM"
    VIDA_UTIL_ANIOS = "VIDA_UTIL_ANIOS"
    # Otros posibles parámetros...
# ------------------------